[package]
name = "libblockid"
version = "0.1.0"
edition = "2024"
description = "Block device identification library"
repository = "https://github.com/rysndavjd/blockid"
keywords = ["partition", "filesystem", "superblock"]
categories = ["filesystem"]
license = "MIT OR Apache-2.0"

[features]
default = ["std"]
std = ["zerocopy/std", "bitflags/std", "rustix/std", "linux-raw-sys/std"]
no_std = []

[dependencies]
bitflags = { version = "2.9.1", default-features = false }
crc = "3.3.0"
zerocopy = { version = "0.8.26", default-features = false, features = ["derive", "alloc"] }
uuid = { version = "1.16.0", features = ["zerocopy"] }
linux-raw-sys = { version = "0.10.0", default-features = false, features = ["ioctl"] }
rustix = { version = "1.0.7", default-features = false, features = ["fs", "alloc"] }
