[package]
name = "libblockid"
version = "0.1.0"
edition = "2024"

[features]
default = ["dos", "gpt", "mac", "bsd"]
dos = []
gpt = []
mac = []
bsd = []

[dependencies]
arrayref = "0.3.9"
bitflags = "2.9.1"
bytemuck = { version = "1.23.0", features = ["derive", "min_const_generics"] }
byteorder = "1.5.0"
rustix = { version = "1.0.7", features = ["fs"] }
uuid = "1.16.0"
