[package]
name = "blockid"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
bitflags = { version = "2.9.1", features = ["std"] }
clap = { version = "4.5.41", features = ["derive"] }
crc-fast = "1.5.0"
libblockid = { path = "../libblockid" }
log = "0.4.27"
rustix = { version = "1.0.7", features = ["fs"] }
simple_logger = "5.0.0"
thiserror = "2.0.12"
uuid = "1.16.0"
