[package]
name = "blockid"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
clap = { version = "4.5.41", features = ["derive"] }
libblockid = { path = "../libblockid" }
rustix = { version = "1.0.7", features = ["fs"] }
uuid = "1.16.0"