[target.aarch64-unknown-linux-gnu]
linker = "aarch64-unknown-linux-gnu-gcc"

[toolchain]
channel = "stable"
components = ["rustc", "rust-std", "cargo", "rust-src", "rustc-dev", "llvm-tools"]
profile = "minimal"